### ISSUE TITLE
NC Podcast Sync - NC lets me authenticate, Pinepods doesn't seem to see it

### ISSUE THREAD

**Issue by cirdanlunae** [madeofpendletonwool/PinePods#206] opened 2024-07-18 06:27 UTC
Hi there!

Pinepods version: 0.6.2
NC version: 29
GPodder Sync NC Plugin version: 3.9.0

When setting up NC Sync, I'm able to put in my domain, and it takes me to NC Authentication. After granting access, I receive a "Account Connected" message from NC. However, Pinepods still says "Current Podcast Sync Server: Not currently syncing with Nextcloud server"

My docker container log only gives me information about startup, no errors/warnings/etc. Not sure where to start with debugging. Thoughts?

**Comment by madeofpendletonwool** [comment] 2024-07-19 00:17
Hi @cirdanlunae! This is actually an issue I'm rolling out a fix for here in the next few days. So I have a good feeling I know what's going on there. What database type are you using? Postgres or Mysql? Also, after giving it some time have your podcasts synced in? It's entirely possible the issue isn't with the nextcloud connection at all but the bug is in the way that current server display pulls from the database.

**Comment by madeofpendletonwool** [comment] 2024-07-22 15:01
I'm going to close this issue now that 0.6.3 is out and I think it should fix the database problem that was causing this bug. Feel free to open a new one if you still have a problem

**Closed by madeofpendletonwool** 2024-07-22 15:01 UTC

**Comment by SirBogner** [comment] 2024-08-05 13:50
I'm currently running into the same problem.
URL is entered -> NC Authentication page opens and Pinepods is authenticated. Then nothing happens in Pinepods.

I'm running Pinepods with MariaDB/MySQL.

**Comment by madeofpendletonwool** [comment] 2024-08-05 13:53
Hi @SirBogner, I'll test the flow with mariadb this morning here. Most of my testing as of late has been with postgres so it's possible there's an issue. I'll get back to you soon!

**Comment by SirBogner** [comment] 2024-08-06 06:23
This morning I glanced at the database logs and the following logs were showing.

> 2024-08-06  6:19:11 105672 [Warning] Aborted connection 105672 to db: 'pinepods' user: 'pinepods' host: '172.17.0.7' (Got an error reading communication packets)

> 2024-08-06  6:19:11 105627 [Warning] Aborted connection 105627 to db: 'pinepods' user: 'pinepods' host: '172.17.0.7' (Got an error reading communication packets)

> 2024-08-06  6:19:11 105624 [Warning] Aborted connection 105624 to db: 'pinepods' user: 'pinepods' host: '172.17.0.7' (Got an error reading communication packets)

> 2024-08-06  6:19:11 105631 [Warning] Aborted connection 105631 to db: 'pinepods' user: 'pinepods' host: '172.17.0.7' (Got an error reading communication packets)

> 2024-08-06  6:19:24 105721 [Warning] Aborted connection 105721 to db: 'unconnected' user: 'unauthenticated' host: '172.17.0.7' (This connection closed normally without authentication)

I hope this helps narrowing down the problem. Tell me if you need anything else 😊
